---
title: "Distribuciones"
author: "Illya Yakymenko"
date: "6 de junio de 2019"
output: html_document
---

```{r}
# Lectura de archivos

library(readr)

dirgeneral <- "dcompleto"
fnhistgeneral <- list.files(dirgeneral, pattern = ".hist")

histgeneral <- new.env()
for(fn in fnhistgeneral){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(dirgeneral, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histgeneral[[envname]] <- hist
}


dirbeta <- "dbeta"
fnhistbeta <- list.files(dirbeta, pattern = ".hist")

histbeta <- new.env()
for(fn in fnhistbeta){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(dirbeta, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histbeta[[envname]] <- hist
}


diralfaprima <- "dalfaprima"
fnhistalfaprima <- list.files(diralfaprima, pattern = ".hist")

histalfaprima <- new.env()
for(fn in fnhistalfaprima){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(diralfaprima, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histalfaprima[[envname]] <- hist
}

diralfaL <- "dalfaL"
fnhistalfaL <- list.files(diralfaL, pattern = ".hist")

histalfaL <- new.env()
for(fn in fnhistalfaL){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(diralfaL, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histalfaL[[envname]] <- hist
}

diralfaR <- "dalfaR"
fnhistalfaR <- list.files(diralfaR, pattern = ".hist")

histalfaR <- new.env()
for(fn in fnhistalfaR){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(diralfaR, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histalfaR[[envname]] <- hist
}


dirppII <- "dppII"
fnhistppII <- list.files(dirppII, pattern = ".hist")

histppII <- new.env()
for(fn in fnhistppII){
  cut <- gregexpr("_", fn)[[1]]
  envname <- substr(fn, 1, cut-1)
  
  hist <- read_table2(paste(dirppII, fn, sep="/"), col_names = F,
                      col_types = cols(X1 = col_character()))
  names(hist) = c("Aminoácido", "Rango", "Valor")
  
  histppII[[envname]] <- hist
}

```


```{r}
histgeneral_por_aa <- new.env()

for(env in ls(histgeneral)){
  histgeneral_por_aa[[env]] <- new.env()
  hist <- histgeneral[[env]]
  histgeneral_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histgeneral_por_aa[[env]][[aa]] <- subhist
  }
  
}

histbeta_por_aa <- new.env()

for(env in ls(histbeta)){
  histbeta_por_aa[[env]] <- new.env()
  hist <- histbeta[[env]]
  histbeta_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histbeta_por_aa[[env]][[aa]] <- subhist
  }
  
}

histalfaprima_por_aa <- new.env()

for(env in ls(histalfaprima)){
  histalfaprima_por_aa[[env]] <- new.env()
  hist <- histalfaprima[[env]]
  histalfaprima_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histalfaprima_por_aa[[env]][[aa]] <- subhist
  }
  
}


histalfaL_por_aa <- new.env()

for(env in ls(histalfaL)){
  histalfaL_por_aa[[env]] <- new.env()
  hist <- histalfaL[[env]]
  histalfaL_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histalfaL_por_aa[[env]][[aa]] <- subhist
  }
  
}


histalfaR_por_aa <- new.env()

for(env in ls(histalfaR)){
  histalfaR_por_aa[[env]] <- new.env()
  hist <- histalfaR[[env]]
  histalfaR_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histalfaR_por_aa[[env]][[aa]] <- subhist
  }
  
}


histppII_por_aa <- new.env()

for(env in ls(histppII)){
  histppII_por_aa[[env]] <- new.env()
  hist <- histppII[[env]]
  histppII_por_aa[[env]][["Todo"]] <- hist
  
  hist$`Aminoácido` <- as.factor(hist$`Aminoácido`)
  aas <- unique(hist$`Aminoácido`)
  
  for(aa in aas){
    subhist <- subset(hist, hist$`Aminoácido` == aa)
    histppII_por_aa[[env]][[aa]] <- subhist
  }
  
}

```

```{r}
aas <- unique(histgeneral[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histgeneral_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histgeneral_por_aa[[env]][[subenv]]$Rango, 
           y = histgeneral_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(general)"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Porcentaje")
    }
    else{
      subenv <- aas[i]
      lines(x = histgeneral_por_aa[[env]][[subenv]]$Rango, 
            y = histgeneral_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```


```{r}
aas <- unique(histbeta[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histbeta_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histbeta_por_aa[[env]][[subenv]]$Rango, 
           y = histbeta_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(Beta)"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Porcentaje")
    }
    else{
      subenv <- aas[i]
      lines(x = histbeta_por_aa[[env]][[subenv]]$Rango, 
            y = histbeta_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```


```{r}
aas <- unique(histalfaprima[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histalfaprima_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histalfaprima_por_aa[[env]][[subenv]]$Rango, 
           y = histalfaprima_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(Alfa\')"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Frecuencia (%)")
    }
    else{
      subenv <- aas[i]
      lines(x = histalfaprima_por_aa[[env]][[subenv]]$Rango, 
            y = histalfaprima_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```

```{r}
aas <- unique(histalfaL[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histalfaL_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histalfaL_por_aa[[env]][[subenv]]$Rango, 
           y = histalfaL_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(Alfa L)"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Frecuencia (%)")
    }
    else{
      subenv <- aas[i]
      lines(x = histalfaL_por_aa[[env]][[subenv]]$Rango, 
            y = histalfaL_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```

```{r}
aas <- unique(histalfaR[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histalfaR_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histalfaR_por_aa[[env]][[subenv]]$Rango, 
           y = histalfaR_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(Alfa R)"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Frecuencia (%)")
    }
    else{
      subenv <- aas[i]
      lines(x = histalfaR_por_aa[[env]][[subenv]]$Rango, 
            y = histalfaR_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```

```{r}
aas <- unique(histppII[["distdPhi"]]$`Aminoácido`)
colores <- rainbow(length(aas))

for(env in ls(histppII_por_aa)){
  mainname <- substr(env, 5, nchar(env))
  
  for(i in seq(length(aas))){
    if(i == 1){
      subenv <- aas[i]
      plot(x = histppII_por_aa[[env]][[subenv]]$Rango, 
           y = histppII_por_aa[[env]][[subenv]]$Valor, type="l",
           main = paste("Distribución", mainname, "(PPII)"), 
           col = colores[[i]], xlab = "Módulo (º)",
           ylab = "Frecuencia (%)")
    }
    else{
      subenv <- aas[i]
      lines(x = histppII_por_aa[[env]][[subenv]]$Rango, 
            y = histppII_por_aa[[env]][[subenv]]$Valor, type = "l",
            col = colores[i])
    }
    
    if(i == length(aas)){
      legend("topright", fill = colores, legend = aas)
    }
  }
}

```




```{r}
tipos <- ls(histgeneral_por_aa)
colores <- rainbow(6)

for(tipo in tipos){
  if (tipo == "distdTCuadrado"){
    limitey = c(0,4)
    limitex = c(0,100)
  }
  else if (tipo == "distdT"){
    limitey = c(0,7)
    limitex = c(0,25)
  }
  else{
    limitey = c(0,4.5)
    limitex = c(-25,25)
  }
  
  plot(x = histgeneral_por_aa[[tipo]][["Global"]]$Rango,
       y = histgeneral_por_aa[[tipo]][["Global"]]$Valor, type = "l", col = colores[1],
       main = paste("Distribución", substr(tipo, 5, nchar(tipo))), 
       xlab = "Módulo (º)", ylab = "Frecuencia (%)", ylim = limitey, xlim = limitex,
       lwd = 2)
  lines(x = histbeta_por_aa[[tipo]][["Global"]]$Rango,
        y = histbeta_por_aa[[tipo]][["Global"]]$Valor, type = "l", col = colores[2],
        lwd = 2)
  lines(x = histalfaprima_por_aa[[tipo]][["Global"]]$Rango,
        y = histalfaprima_por_aa[[tipo]][["Global"]]$Valor, type = "l", 
        col = colores[3], lwd = 2)
  lines(x = histalfaL_por_aa[[tipo]][["Global"]]$Rango,
        y = histalfaL_por_aa[[tipo]][["Global"]]$Valor, type = "l", 
        col = colores[4], lwd = 2)
  lines(x = histalfaR_por_aa[[tipo]][["Global"]]$Rango,
        y = histalfaR_por_aa[[tipo]][["Global"]]$Valor, type = "l", 
        col = colores[5], lwd = 2)
  lines(x = histppII_por_aa[[tipo]][["Global"]]$Rango,
        y = histppII_por_aa[[tipo]][["Global"]]$Valor, type = "l", 
        col = colores[6], lwd = 2)
  
  legend("topright", fill = colores, 
         legend = c("Espectro completo", "Región beta", "Región alfa\'", 
                    "Región alfa L", "Región alfa R", "Región PPII"))
}


```


```{r}
dTCgeneral <- histgeneral_por_aa[["distdTCuadrado"]][["Global"]]
dTCgeneral <- subset(dTCgeneral, dTCgeneral$Rango >= 0)
x <- dTCgeneral$Rango
y <- dTCgeneral$Valor
exp.general <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.general)

dTCbeta <- histbeta_por_aa[["distdTCuadrado"]][["Global"]]
dTCbeta <- subset(dTCbeta, dTCbeta$Rango >= 0)
x <- dTCbeta$Rango
y <- dTCbeta$Valor
exp.beta <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.beta)

dTCalfaL <- histalfaL_por_aa[["distdTCuadrado"]][["Global"]]
dTCalfaL <- subset(dTCalfaL, dTCalfaL$Rango >= 0)
x <- dTCalfaL$Rango
y <- dTCalfaL$Valor
exp.alfaL <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.alfaL)

dTCalfaR <- histalfaR_por_aa[["distdTCuadrado"]][["Global"]]
dTCalfaR <- subset(dTCalfaR, dTCalfaR$Rango >= 0)
x <- dTCalfaR$Rango
y <- dTCalfaR$Valor
exp.alfaR <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.alfaR)

dTCalfaprima <- histalfaprima_por_aa[["distdTCuadrado"]][["Global"]]
dTCalfaprima <- subset(dTCalfaprima, dTCalfaprima$Rango >= 0)
x <- dTCalfaprima$Rango
y <- dTCalfaprima$Valor
exp.alfaprima <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.alfaprima)

dTCppII <- histppII_por_aa[["distdTCuadrado"]][["Global"]]
dTCppII <- subset(dTCppII, dTCppII$Rango >= 0)
x <- dTCppII$Rango
y <- dTCppII$Valor
exp.ppII <- nls(y~(a*exp(1)**(- x/b)), 
                   start = list(a = 1, b = 10))
summary(exp.ppII)
```

```{r}
plot(x = histgeneral_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histgeneral_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histgeneral_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histgeneral_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "General", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCgeneral$Rango, predict(exp.general), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.general$m$getAllPars()[1])
b <- as.numeric(exp.general$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)


plot(x = histbeta_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histbeta_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histbeta_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histbeta_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "Beta", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCbeta$Rango, predict(exp.beta), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.beta$m$getAllPars()[1])
b <- as.numeric(exp.beta$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)


plot(x = histalfaL_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histalfaL_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histalfaL_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histalfaL_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "Alfa L", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCalfaL$Rango, predict(exp.alfaL), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.alfaL$m$getAllPars()[1])
b <- as.numeric(exp.alfaL$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)


plot(x = histalfaR_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histalfaR_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histalfaR_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histalfaR_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "Alfa R", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCalfaR$Rango, predict(exp.alfaR), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.alfaR$m$getAllPars()[1])
b <- as.numeric(exp.alfaR$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)


plot(x = histalfaprima_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histalfaprima_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histalfaprima_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histalfaprima_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "Alfa\'", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCalfaprima$Rango, predict(exp.alfaprima), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.alfaprima$m$getAllPars()[1])
b <- as.numeric(exp.alfaprima$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)


plot(x = histppII_por_aa[["distdTCuadrado"]][["Global"]]$Rango[histppII_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      y = histppII_por_aa[["distdTCuadrado"]][["Global"]]$Valor[histppII_por_aa[["distdTCuadrado"]][["Global"]]$Rango >= 0],
      col = "red", type = "l", main = "PPII", xlim = c(0,100),
     xlab = "Módulo(º)", ylab = "Frecuencia(%)", lwd = 2)
lines(dTCppII$Rango, predict(exp.ppII), lwd = 2)
legend("topright", fill = c("red", "black"), legend = c("Experimental", "Ajuste exponencial"))
a <- as.numeric(exp.ppII$m$getAllPars()[1])
b <- as.numeric(exp.ppII$m$getAllPars()[2])
mtext(paste("f(x) = ", round(a, 4), "*e^(x/", round(b, 4), ")"  ,sep = ""), line = -2)



```


```{r}
plot(x = histalfaL[["distdPhi"]]$Rango, y = histalfaL[["distdPhi"]]$Valor, type = "l",
     col = "red", main = "Región alfa L", xlab = "Desplazamiento (º)",
     ylab = "Frecuencia (%)", ylim = c(0,4), xlim = c(-15, 15))
lines(x = histalfaL[["distdPsi"]]$Rango, y = histalfaL[["distdPsi"]]$Valor, type = "l",
     col = "blue")
legend("topright", fill = c("red", "blue"), legend = c("dPhi", "dPsi"))

plot(x = histalfaR[["distdPhi"]]$Rango, y = histalfaR[["distdPhi"]]$Valor, type = "l",
     col = "red", main = "Región alfa R", xlab = "Desplazamiento (º)",
     ylab = "Frecuencia (%)", ylim = c(0,4), xlim = c(-15, 15))
lines(x = histalfaR[["distdPsi"]]$Rango, y = histalfaR[["distdPsi"]]$Valor, type = "l",
     col = "blue")
legend("topright", fill = c("red", "blue"), legend = c("dPhi", "dPsi"))

plot(x = histbeta[["distdPhi"]]$Rango, y = histbeta[["distdPhi"]]$Valor, type = "l",
     col = "red", main = "Región beta", xlab = "Desplazamiento (º)",
     ylab = "Frecuencia (%)", ylim = c(0,4), xlim = c(-15, 15))
lines(x = histbeta[["distdPsi"]]$Rango, y = histbeta[["distdPsi"]]$Valor, type = "l",
     col = "blue")
legend("topright", fill = c("red", "blue"), legend = c("dPhi", "dPsi"))

plot(x = histppII[["distdPhi"]]$Rango, y = histppII[["distdPhi"]]$Valor, type = "l",
     col = "red", main = "Región ppII", xlab = "Desplazamiento (º)",
     ylab = "Frecuencia (%)", ylim = c(0,4), xlim = c(-15, 15))
lines(x = histppII[["distdPsi"]]$Rango, y = histppII[["distdPsi"]]$Valor, type = "l",
     col = "blue")
legend("topright", fill = c("red", "blue"), legend = c("dPhi", "dPsi"))

plot(x = histalfaprima[["distdPhi"]]$Rango, y = histalfaprima[["distdPhi"]]$Valor, type = "l",
     col = "red", main = "Región alfa\'", xlab = "Desplazamiento (º)",
     ylab = "Frecuencia (%)", ylim = c(0,4), xlim = c(-15, 15))
lines(x = histalfaprima[["distdPsi"]]$Rango, y = histalfaprima[["distdPsi"]]$Valor, type = "l",
     col = "blue")
legend("topright", fill = c("red", "blue"), legend = c("dPhi", "dPsi"))


```



```{r}
distPhi <- histgeneral[["distdPhi"]]
distPhi <- subset(distPhi, distPhi$`Aminoácido` == "Global")
distPhi$Valor <- distPhi$Valor / sum(distPhi$Valor)

axpos <- seq(-20, 20, 10)
axtext <- as.character(axpos)
axtext <- paste(axtext, "º", sep = "")

plot(x = distPhi$Rango, y = distPhi$Valor, type = "s", lwd = 2, 
     main = expression(paste("Distribución de ", Delta*Phi)),
     xlab = expression(Delta*Phi), ylab = "Densidad",
     xlim = c(-20, 20), ylim = c(0, 0.035), xaxt = "n")
lines(x = distPhi$Rango, y = distPhi$Valor, type = "l", col = "red")

axis(side = 1, at=axpos, labels = axtext)


mtext(text = expression(paste(mu, " = 0.00001584º")), at = 15, line = -2)
mtext(text = expression(paste(sigma, " = 2.66073604º")), at = 15, line = -3)



distPsi <- histgeneral[["distdPsi"]]
distPsi <- subset(distPsi, distPsi$`Aminoácido` == "Global")
distPsi$Valor <- distPsi$Valor / sum(distPsi$Valor)

plot(x = distPsi$Rango, y = distPsi$Valor, type = "s", lwd = 2, 
     main = expression(paste("Distribución de ", Delta*Psi)),
     xlab = expression(Delta*Psi), ylab = "Densidad",
     xlim = c(-20, 20), ylim = c(0, 0.035), xaxt = "n")
lines(x = distPsi$Rango, y = distPsi$Valor, type = "l", col = "red")

axis(side = 1, at=axpos, labels = axtext)

mtext(text = expression(paste(mu, " = -0.00003125º")), at = 15, line = -2)
mtext(text = expression(paste(sigma, " = 2.52182212º")), at = 15, line = -3)

```














