---
title: "Mapas de desviaciones estándar"
author: "Illya Yakymenko"
date: "18 de junio de 2019"
output: html_document
---

```{r include=F}
library(readr)
library(plot3D)

dir <- "mapasDE"
matrices <- list.files(dir)

mapas <- new.env()

for(m in matrices){
  endpos <- gregexpr(")", m)[[1]]
  envname <- substr(m, 12, endpos)
  
  matrix <- read_table2(paste(dir, m, sep = "/"), col_names = F)
  dim <- dim(matrix)[1]
  matrix <- t(matrix[1:dim, 1:dim])
  matrix[matrix < -5] <- NA
  
  mapas[[envname]] <- matrix
}


```


```{r}

x <- seq(-180, 179)
y <- seq(-180, 179)

axpos <- seq(-150, 150, 50)
axtext <- as.character(axpos)
axtext <- paste(axtext, "º", sep = "")


par(pin = c(3.32, 2.75))
image2D(x = x, y = y, z = mapas[["dPhi(i)"]], 
        main = expression(sigma[Delta~Phi[i]]), cex.main = 1.75,
        rasterImage = T, zlim = c(0,4.5),
        xlab = expression(Phi[i]), ylab = expression(Psi[i]), 
        xaxt = "n", yaxt = "n")
par(pin = c(3.32, 2.75))
axis(side = 2, at=axpos, labels = axtext, cex.axis = 0.70)
axis(side = 1, at=axpos, labels = axtext, cex.axis = 0.70)


par(pin = c(3.32, 2.75))
image2D(x = x, y = y, z = mapas[["dPsi(i)"]], 
        main = expression(sigma[Delta~Psi[i]]), cex.main = 1.75,
        rasterImage = T, zlim = c(0,4.5),
        xlab = expression(Phi[i]), ylab = expression(Psi[i]),
        xaxt = "n", yaxt = "n")
par(pin = c(3.32, 2.75))
axis(side = 2, at=axpos, labels = axtext, cex.axis = 0.70)
axis(side = 1, at=axpos, labels = axtext, cex.axis = 0.70)


par(pin = c(3.32, 2.75))
image2D(x = x, y = y, z = mapas[["dPsi(i-1)"]], main = expression(sigma[Delta~Psi[i-1]]), cex.main = 1.75,
        rasterImage = T, zlim = c(0,4.5),
        xlab = expression(Phi[i]), ylab = expression(Psi[i]),
        xaxt = "n", yaxt = "n")
par(pin = c(3.32, 2.75))
axis(side = 2, at=axpos, labels = axtext, cex.axis = 0.70)
axis(side = 1, at=axpos, labels = axtext, cex.axis = 0.70)

par(pin = c(3.32, 2.75))
image2D(x = x, y = y, z = mapas[["dPhi(i+1)"]], main = expression(sigma[Delta~Phi[i+1]]), cex.main = 1.75,
        rasterImage = T, zlim = c(0,4.5),
        xlab = expression(Phi[i]), ylab = expression(Psi[i]),
        xaxt = "n", yaxt = "n")
par(pin = c(3.32, 2.75))
axis(side = 2, at=axpos, labels = axtext, cex.axis = 0.70)
axis(side = 1, at=axpos, labels = axtext, cex.axis = 0.70)
```