---
title: "Máximos y mínimos módulos"
author: "Illya Yakymenko"
date: "2 de junio de 2019"
output: html_document
---

```{r}
library(plot3D)
library(readr)

mmaxfn <- "modulos40.dat"
mmax <- read_table2(mmaxfn,  col_names = FALSE)
cn <- c("Módulo", "Aminoácido", "Phi-1", "Psi-1", "Phi", "Psi", "dPhi", "dPsi", "Tiempo")

names(mmax) <- cn

mminfn <- "menores0.1.dat"
mmin <- read_table2(mminfn,  col_names = FALSE)

names(mmin) <- cn


rama360 <- read_table2("rama360/ramachandran_decala-eqNVE_1_112_resol360_global.matrix", col_names = FALSE)

rama360 <- as.matrix(rama360)
rama360[rama360 <0] <- NA

corr360 <- read_table2("c360_por_aa/correlaciones_decala-eqNVE_1_112_resol360_global/correlaciones_decala-eqNVE_1_112_resol360_Phi0-Psi0-global.matrix", col_names = FALSE)

corr360 <- t(as.matrix(corr360))
corr360[corr360 <-2] <- NA

```

```{r}
matrix_ext <- function(matrix){
  nr <- nrow(matrix)
  nc <- ncol(matrix)
  
  mat_ext <- matrix(nrow = nr*3, ncol = nc*3)
  mat_ext[1:nr, 1:nc] <- matrix
  mat_ext[1:nr, (nc+1):(2*nc)] <- matrix
  mat_ext[1:nr, (2*nc+1):(3*nc)] <- matrix
  mat_ext[(nr+1):(2*nr), 1:nc] <- matrix
  mat_ext[(nr+1):(2*nr), (nc+1):(2*nc)] <- matrix
  mat_ext[(nr+1):(2*nr), (2*nc+1):(3*nc)] <- matrix
  mat_ext[(2*nr+1):(3*nr), 1:nc] <- matrix
  mat_ext[(2*nr+1):(3*nr), (nc+1):(2*nc)] <- matrix
  mat_ext[(2*nr+1):(3*nr), (2*nc+1):(3*nc)] <- matrix
  
  return(mat_ext)
}

rama_ext <- matrix_ext(rama360)
corr_ext <- matrix_ext(corr360)

rama_ext <- rama_ext[341:740, 341:740]
corr_ext <- corr_ext[341:740, 341:740]
```

```{r}
#Acotación del órden de módulos

mmin <- mmin[order(mmin$`Módulo`, decreasing = F), ]
mmax <- mmax[order(mmax$`Módulo`, decreasing = T), ]

submmin <- new.env()
submmax <- new.env()

cortes <- c(10, 100, 1000, 2000, 5000, 10000, 25000, 50000)

for(c in cortes){
  env <- as.character(c)
  
  submmin[[env]] <- mmin[1:c,]
  submmax[[env]] <- mmax[1:c,]
}
```

### Histogramas por aminoácido

```{r}
hist(mmax$`Aminoácido`, breaks = seq(0,max(mmax$`Aminoácido`, 1)), 
     main = paste("Áminoácidos máximos: N=", nrow(mmax)), xlab = "Aminoácido",
     ylab = "Frecuencia", freq = F)
hist(mmin$`Aminoácido`, breaks = seq(0,max(mmin$`Aminoácido`, 1)), 
     main = paste("Áminoácidos mínimos: N=", nrow(mmin)), xlab = "Aminoácido",
     ylab = "Frecuencia", freq = F)

for (c in cortes){
  env <- as.character(c)
  
  submin <- submmin[[env]]
  submax <- submmax[[env]]
  
  hist(submax$`Aminoácido`, breaks = seq(0,10), 
     main = paste("Áminoácidos máximos: N=", nrow(submax)), xlab = "Aminoácido",
     ylab = "Frecuencia", freq = F)
  hist(submin$`Aminoácido`, breaks = seq(0,10), 
     main = paste("Áminoácidos mínimos: N=", nrow(submin)), xlab = "Aminoácido",
     ylab = "Frecuencia", freq = F)
}
```

```{r}
prob_aa_max <- matrix(ncol = 3, nrow=0)

for (c in cortes[-1]){
  env <- as.character(c)
  aas <- submmax[[env]]$`Aminoácido`
  
  probs <- matrix(nrow=10, ncol=3)
  aat <- table(aas)
  
  for (i in seq(10)){
    pr <- (aat[names(aat)== i]/length(aas))*100
    
    probs[i,] <- c(c, i, pr)
  }
  
  prob_aa_max <- rbind(prob_aa_max, probs)
}

```

```{r}
colores <- rainbow(length(cortes)-1)

prob_aa_max <- as.data.frame(prob_aa_max)
names(prob_aa_max) <- c("Subset", "Aminoácido", "Porcentaje")

for(c in seq(length(cortes[-1]))){
  sub <- subset(prob_aa_max, prob_aa_max$Subset == cortes[c+1])
  
  if(c == 1){
    plot(x = sub$`Aminoácido`, y = sub$Porcentaje, col = colores[c],
         main = "Evolución del porcentaje de aminoácidos de mayores módulos", 
         xlab = "Aminoácido", ylab = "Porcentaje (%)", type = "l", ylim = c(0,25),
         lwd = 2)
  }
  else {
    lines(x = sub$`Aminoácido`, y = sub$Porcentaje, col = colores[c], lwd = 2)
  }
  
  if(c == length(cortes[-1])){
    legend("topright", fill = colores, legend = cortes[-1])
  }
}

```

```{r}
prob_aa_min <- matrix(ncol = 3, nrow=0)

for (c in cortes[-1]){
  env <- as.character(c)
  aas <- submmin[[env]]$`Aminoácido`
  
  probs <- matrix(nrow=10, ncol=3)
  aat <- table(aas)
  
  for (i in seq(10)){
    pr <- (aat[names(aat)== i]/length(aas))*100
    
    probs[i,] <- c(c, i, pr)
  }
  
  prob_aa_min <- rbind(prob_aa_min, probs)
}

```

```{r}
colores <- rainbow(length(cortes)-1)

prob_aa_min <- as.data.frame(prob_aa_min)
names(prob_aa_min) <- c("Subset", "Aminoácido", "Porcentaje")

for(c in seq(length(cortes[-1]))){
  sub <- subset(prob_aa_min, prob_aa_min$Subset == cortes[c+1])
  
  if(c == 1){
    plot(x = sub$`Aminoácido`, y = sub$Porcentaje, col = colores[c],
         main = "Evolución del porcentaje de aminoácidos de mayores módulos", 
         xlab = "Aminoácido", ylab = "Porcentaje (%)", type = "l", ylim = c(0,25),
         lwd = 2)
  }
  else {
    lines(x = sub$`Aminoácido`, y = sub$Porcentaje, col = colores[c], lwd = 2)
  }
  
  if(c == length(cortes[-1])){
    legend("topright", fill = colores, legend = cortes[-1])
  }
}

```

### Representación de módulos máximos

```{r}
x = seq(-200, 200, 1)[-401]
y = seq(-200, 200, 1)[-401]

for(c in cortes){
  env <- as.character(c)
  sub <- submmax[[env]]
  
  subPhi <- sub$`Phi-1` + sub$dPhi
  subPsi <- sub$`Psi-1` + sub$dPsi

  par(pin = c(3.32,2.75))
  image2D(x = x, y = y, 
            z = rama_ext, lighting = T, main = paste("Máximos: N=", env),
            clog = T, xlab = expression(Phi), ylab = expression(Psi), 
            #clab = c("Densidad en" ,"escala logarítmica"), 
            xlim = c(-200, 200),
            ylim = c(-200, 200), 
            colkey = list(cex.clab = 0.75), rasterImage = T,
            contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
  
  arrows(x0 = sub$`Phi-1`, y0 = sub$`Psi-1`, x1 = subPhi, y1 = subPsi, length = 0.05)
  
  par(pin = c(3.32,2.75))
  image2D(x = x, y = y, 
            z = corr_ext, lighting = F, main = paste("Máximos: N=", env),
            clog = F, xlab = expression(Phi), ylab = expression(Psi), 
            #clab = c("Densidad en" ,"escala logarítmica"), 
            xlim = c(-200, 200),
            ylim = c(-200, 200),
            zlim = c(-1,1),
            colkey = list(cex.clab = 0.75), rasterImage = T,
            contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
  
  arrows(x0 = sub$`Phi-1`, y0 = sub$`Psi-1`, x1 = subPhi, y1 = subPsi, length = 0.05)
}
```

### Representación de módulos mínimos

```{r}
x = seq(-200, 200, 1)[-401]
y = seq(-200, 200, 1)[-401]

for(c in cortes){
  env <- as.character(c)
  sub <- submmin[[env]]
  
  subPhi <- sub$`Phi-1` + sub$dPhi
  subPsi <- sub$`Psi-1` + sub$dPsi

  par(pin = c(3.32,2.75))
  image2D(x = x, y = y, 
            z = rama_ext, lighting = T, main = paste("Mínimos N=", env),
            clog = T, xlab = expression(Phi), ylab = expression(Psi), 
            #clab = c("Densidad en" ,"escala logarítmica"), 
            xlim = c(-200, 200),
            ylim = c(-200, 200), 
            colkey = list(cex.clab = 0.75), rasterImage = T,
            contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
  
  points(x = sub$`Phi-1`, y = sub$`Psi-1`, pch = 20, cex= 0.25)
  
  par(pin = c(3.32,2.75))
  image2D(x = x, y = y, 
            z = corr_ext, lighting = F, main = paste("Mínimos N=", env),
            clog = F, xlab = expression(Phi), ylab = expression(Psi), 
            #clab = c("Densidad en" ,"escala logarítmica"), 
            xlim = c(-200, 200),
            ylim = c(-200, 200),
            zlim = c(-1,1),
            colkey = list(cex.clab = 0.75), rasterImage = T,
            contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
  
  points(x = sub$`Phi-1`, y = sub$`Psi-1`, pch = 20, cex= 0.25)
}
```

```{r}
# moddPhi <- submmin[["50000"]]$dPhi
# moddPsi <- submmin[["50000"]]$dPsi
# modulo <- submmin[["50000"]]$`Módulo`
# 
# corr_min <- matrix(nrow = length(modulo), ncol = 2)
# 
# for (i in seq(2,length(modulo))){
#   N <- length(moddPhi[1:i])
#   SPhiPsi <- sum(moddPhi[1:i]*moddPsi[1:i])
#   SPhi <- sum(moddPhi[1:i])
#   SPsi <- sum(moddPsi[1:i])
#   SPhiCuad <- sum(moddPhi[1:i]*moddPhi[1:i])
#   SPsiCuad <- sum(moddPsi[1:i]*moddPsi[1:i])
# 
#   r <- (N*SPhiPsi - SPhi*SPsi)/(sqrt(N*SPhiCuad - SPhi*SPhi) * sqrt(N*SPsiCuad - SPsi*SPsi))
# 
#   corr_min[i,1] <- i
#   corr_min[i,2] <- r
# 
#   print(i)
# }
# 
# corr_min <- as.data.frame(corr_min)
# names(corr_min) <- c("Número módulos", "Correlación")
# saveRDS(corr_min, "corrmin")
```


```{r}
# moddPhi <- submmax[["50000"]]$dPhi
# moddPsi <- submmax[["50000"]]$dPsi
# modulo <- submmax[["50000"]]$`Módulo`
# 
# corr_max <- matrix(nrow = length(modulo), ncol = 2)
# 
# for (i in seq(2,length(modulo))){
#   N <- length(moddPhi[1:i])
#   SPhiPsi <- sum(moddPhi[1:i]*moddPsi[1:i])
#   SPhi <- sum(moddPhi[1:i])
#   SPsi <- sum(moddPsi[1:i])
#   SPhiCuad <- sum(moddPhi[1:i]*moddPhi[1:i])
#   SPsiCuad <- sum(moddPsi[1:i]*moddPsi[1:i])
# 
#   r <- (N*SPhiPsi - SPhi*SPsi)/(sqrt(N*SPhiCuad - SPhi*SPhi) * sqrt(N*SPsiCuad - SPsi*SPsi))
# 
#   corr_max[i,1] <- i
#   corr_max[i,2] <- r
# 
#   print(i)
# }
# 
# corr_max <- as.data.frame(corr_max)
# names(corr_max) <- c("Número módulos", "Correlación")
# saveRDS(corr_max, "corrmax")
```

```{r}
corr_max <- readRDS("corrmax")
corr_min <- readRDS("corrmin")
```


### Evolución de la correlación

```{r}
plot(x = corr_max$`Número módulos`, y = corr_max$`Correlación`, col = "red", 
     ylim = c(-1,1), type = "l", xlab = "Número de módulos", ylab = "Correlación",
     main = "Evolución de la correlación")
lines(x = corr_min$`Número módulos`, y = corr_min$`Correlación`, col = "blue")
legend("topright", fill = c("red", "blue"), 
       legend = c("Módulos máximos", "Módulos mínimos"))
```

```{r}
plot(x = corr_max$`Número módulos`, y = corr_max$`Correlación`, col = "red",
     type = "l", xlab = "Número de módulos", ylab = "Correlación",
     main = "Evolución de la correlación de módulos máximos")
```

```{r}
plot(x = corr_min$`Número módulos`, y = corr_min$`Correlación`, col = "blue",
     type = "l", xlab = "Número de módulos", ylab = "Correlación",
     main = "Evolución de la correlación de módulos mínimos")
```

```{r}
corr_mayores <- readRDS("corr_mayores")

plot(x = corr_mayores[,1], y = corr_mayores[,2], col = "red",
     type = "l", xlab = "Número de módulos", ylab = "Correlación",
     main = "Evolución de la correlación de módulos máximos")
```



```{r}
plot(density(submmax[["50000"]]$Tiempo), main = "Evolución temporal de los módulos", 
     xlab = "Tiempo", ylab = "Densidad", col = "red", cex.axis = 0.75)
lines(density(submmin[["50000"]]$Tiempo), col = "blue")
legend("bottom", fill = c("red", "blue"), 
       legend = c("Mayores módulos", "Menores módulos"))

```

### Representación de módulos respecto al origen

```{r}
for (c in cortes){
  env <- as.character(c)
  
  par(pin = c(2.5, 2.5))
  points2D(x = submmax[[env]]$dPhi, y = submmax[[env]]$dPsi, asp = 1, 
           xlab = "Desplazamiento Phi", ylab = "Desplazamiento Psi", 
           main = paste("Mayores desplazamientos: N=", env), cex = 0.1, pch = 20, 
           col = "black", cex.axis = 0.75)
  abline(v=0)
  abline(h=0)
}

for (c in cortes){
  env <- as.character(c)
  par(pin = c(2.5, 2.5))
  points2D(x = submmin[[env]]$dPhi, y = submmin[[env]]$dPsi, asp = 1, 
           xlab = "Desplazamiento Phi", ylab = "Desplazamiento Psi", 
           main = paste("Menores desplazamientos: N=", env), cex = 0.1, pch = 20, 
           col = "black", xlim = c(-0.015, 0.015), ylim = c(-0.015, 0.015), 
           cex.axis = 0.75)
  abline(v=0)
  abline(h=0)
}
```

```{r}
library(magick)

x = seq(-200, 200, 1)[-401]
y = seq(-200, 200, 1)[-401]

png(file = "maximos%02d.png", width = 500, height = 500)
  for(c in cortes){
    env <- as.character(c)
    sub <- submmax[[env]]
    
    subPhi <- sub$`Phi-1` + sub$dPhi
    subPsi <- sub$`Psi-1` + sub$dPsi
    
    par(pin = c(3.32,2.75))
    image2D(x = x, y = y, 
              z = corr_ext, lighting = F, main = paste("Máximos: N=", env),
              clog = F, xlab = expression(Phi), ylab = expression(Psi), 
              #clab = c("Densidad en" ,"escala logarítmica"), 
              xlim = c(-200, 200),
              ylim = c(-200, 200),
              zlim = c(-1,1),
              colkey = list(cex.clab = 0.75), rasterImage = T,
              contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
    
    arrows(x0 = sub$`Phi-1`, y0 = sub$`Psi-1`, x1 = subPhi, y1 = subPsi, length = 0.05)
  }
dev.off()

pngs <- image_read(list.files(pattern = ".png"))

gif_max <- image_animate(pngs, fps = 1)

gif_max

image_write(gif_max, "MayoresModulos.gif")

file.remove(list.files(pattern = ".png"))
```

```{r}
x = seq(-200, 200, 1)[-401]
y = seq(-200, 200, 1)[-401]

png(file = "maximosrama%02d.png", width = 500, height = 500)
  for(c in cortes){
    env <- as.character(c)
    sub <- submmax[[env]]
    
    subPhi <- sub$`Phi-1` + sub$dPhi
    subPsi <- sub$`Psi-1` + sub$dPsi
    
    par(pin = c(3.32,2.75))
    image2D(x = x, y = y, 
              z = rama_ext, lighting = F, main = paste("Máximos: N=", env),
              clog = T, xlab = expression(Phi), ylab = expression(Psi), 
              #clab = c("Densidad en" ,"escala logarítmica"), 
              xlim = c(-200, 200),
              ylim = c(-200, 200),
              #zlim = c(-1,1),
              colkey = list(cex.clab = 0.75), rasterImage = T,
              contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
    
    arrows(x0 = sub$`Phi-1`, y0 = sub$`Psi-1`, x1 = subPhi, y1 = subPsi, length = 0.05)
  }
dev.off()

pngs <- image_read(list.files(pattern = ".png"))

gif_max_rama <- image_animate(pngs, fps = 1)

gif_max_rama

image_write(gif_max_rama, "MayoresModulosRamachandran.gif")

file.remove(list.files(pattern = ".png"))
```



```{r}
png(file = "minimos%02d.png", width = 500, height = 500)
  for(c in cortes){
    env <- as.character(c)
    sub <- submmin[[env]]
    
    par(pin = c(3.32,2.75))
    image2D(x = x, y = y, 
            z = rama_ext, lighting = T, main = paste("Mínimos N=", env),
            clog = T, xlab = expression(Phi), ylab = expression(Psi), 
            #clab = c("Densidad en" ,"escala logarítmica"), 
            xlim = c(-200, 200),
            ylim = c(-200, 200), 
            colkey = list(cex.clab = 0.75), rasterImage = T,
            contour = F, asp = 1, cex.axis = 0.75, alpha = 0.75)
  
    points(x = sub$`Phi-1`, y = sub$`Psi-1`, pch = 20, cex= 0.25)
  }
dev.off()

pngs <- image_read(list.files(pattern = ".png"))

gif_min <- image_animate(pngs, fps = 1)

gif_min

image_write(gif_min, "MenoresModulos.gif")

file.remove(list.files(pattern = ".png"))
```


```{r}
png(file = "maximospuntos%02d.png", width = 400, height = 400)
  for (c in cortes){
  env <- as.character(c)
  
  par(pin = c(2.5, 2.5))
  points2D(x = submmax[[env]]$dPhi, y = submmax[[env]]$dPsi, asp = 1, 
           xlab = "Desplazamiento Phi", ylab = "Desplazamiento Psi", 
           main = paste("Mayores desplazamientos: N=", env), cex = 0.1, pch = 20, 
           col = "black", cex.axis = 0.75, xlim = c(-20, 20), ylim = c(-20, 20))
  abline(v=0)
  abline(h=0)
  }
  
dev.off()

pngs <- image_read(list.files(pattern = ".png"))

gif_despmax <- image_animate(pngs, fps = 1)

gif_despmax

image_write(gif_despmax, "DesplazamientosMaximos.gif")

file.remove(list.files(pattern = ".png"))
```


```{r}
png(file = "minimospuntos%02d.png", width = 400, height = 400)
  for (c in cortes){
  env <- as.character(c)
  par(pin = c(2.5, 2.5))
  points2D(x = submmin[[env]]$dPhi, y = submmin[[env]]$dPsi, asp = 1, 
           xlab = "Desplazamiento Phi", ylab = "Desplazamiento Psi", 
           main = paste("Menores desplazamientos: N=", env), cex = 0.1, pch = 20, 
           col = "black", xlim = c(-0.015, 0.015), ylim = c(-0.015, 0.015), 
           cex.axis = 0.75)
  abline(v=0)
  abline(h=0)
}
  
dev.off()

pngs <- image_read(list.files(pattern = ".png"))

gif_despmin <- image_animate(pngs, fps = 1)

gif_despmin

image_write(gif_despmin, "DesplazamientosMaximos.gif")

file.remove(list.files(pattern = ".png"))
```















